###################################################
# Install and cache the translation command dependencies in a reusable action.
#
# Ideally:
# 1. Master installs and caches the composer dependencies.
# 2. Pull requests and deployments can reuse the cached dependencies.
#
# inputs:
#    dir: The directory of the plugin to build translations for.
#
# @version 1.0.3
#
###################################################

name: Install Translate Composer
description: Install Translate Command Dependencies

inputs:
  dir:
    description: Directory of the plugin to build translations for.
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Translate CLI
      uses: actions/cache@v4
      id: cache-translate-cli
      with:
        path: /tmp/composer-cache
        key: translate-cli-${{ hashFiles( format( '{0}/dev/translate-cli/composer.lock', inputs.dir ) ) }}

    - name: Install Translate Command Composer Dependencies
      uses: php-actions/composer@v6
      with:
        args: --no-plugins --no-scripts --prefer-dist
        working_dir: ${{ inputs.dir }}/dev/translate-cli
