###################################################
# Install and cache the translation command dependencies in a reusable action.
#
# Ideally:
# 1. Master installs and caches the composer dependencies.
# 2. Pull requests and deployments can reuse the cached dependencies.
#
# env:
#   BASIC: Directory slug for the BASIC plugin.
#   PRO: Directory slug for the PRO plugin.
#
# @version 0.0.5
#
###################################################

name: Install Translate Command Composer
description: Install Translate Command Dependencies

runs:
  using: "composite"
  steps:
    - name: Cache Translate CLI
      uses: actions/cache@v3
      id: restore-translate-cli
      with:
        path: /tmp/composer-cache
        key: translate-cli-${{ hashFiles( format( 'content/plugins/{0}/dev/translate-cli/composer.lock', env.BASIC ), format( 'content/plugins/{0}/dev/translate-cli/composer.lock', env.PRO ) ) }}

    - name: Install Basic Translate Command Composer Dependencies
      uses: php-actions/composer@v6
      with:
        args: --no-plugins --no-scripts --prefer-dist
        working_dir: content/plugins/${{ env.BASIC }}/dev/translate-cli

    - name: Install PRO Translate Command Composer Dependencies
      uses: php-actions/composer@v6
      with:
        args: --no-plugins --no-scripts --prefer-dist
        working_dir: content/plugins/${{ env.PRO }}/dev/translate-cli
