###################################################
# Install and cache the translation command dependencies in a reusable action.
#
# Ideally:
# 1. Master installs and caches the composer dependencies.
# 2. Pull requests and deployments can reuse the cached dependencies.
#
# inputs:
#    dir: The directory of the plugin to build translations for.
#
# @version 1.1.0
#
###################################################

name: Install Translate Composer
description: Install Translate Command Dependencies

inputs:
  dir:
    description: Directory of the plugin to build translations for.
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Translate CLI
      uses: actions/cache@v4
      id: cache-translate-cli
      with:
        path: ${{ inputs.dir }}/dev/translate-cli/vendor
        key: translate-cli-${{ hashFiles( format( '{0}/dev/translate-cli/composer.lock', inputs.dir ) ) }}

    - if: ${{ steps.cache-translate-cli.outputs.cache-hit != 'true' }}
      name: Install Translate Command Composer Dependencies
      run: composer install --working-dir ${{ inputs.dir }}/dev/translate-cli --no-plugins --no-scripts --prefer-dist
      shell: bash
