###################################################
# Install and cache the phpstan dependency in a reusable action.
#
# Ideally:
# 1. Master installs and caches the phpstan dependency.
# 2. Pull can reuse the cached phpstan dependency.
#
# env:
#   PHPSTAN_VERSION: Version of lipemat/phpstan-wordpress to install.
#                    - Typically set via repository variables on GitHub.
#   STUBS_VERSION: Optional version of php-stubs/wordpress-stubs to install.
#                  - Defaults to the latest version.
# inputs:
#   alwaysCache: Optionally always cache the PHPStan dependencies regardless
#                of the branch.
#
# @version 0.4.1
#
###################################################

name: Install PHPStan
description: Install PHPStan and its dependencies.

inputs:
  alwaysCache:
    description: Always cache the PHPStan dependencies regardless of the branch.
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Restore PHPStan from Cache
      uses: actions/cache/restore@v4
      id: restore-phpstan
      with:
        path: |
          phpstan
          /tmp/phpstan
        key: phpstan-${{ env.PHPSTAN_VERSION }}-${{ env.STUBS_VERSION }}

    - if: ${{ steps.restore-phpstan.outputs.cache-hit != 'true' }}
      name: Install PHPStan
      uses: actions/checkout@v4
      with:
        repository: lipemat/phpstan-wordpress
        path: phpstan
        show-progress: false
        ref: ${{ env.PHPSTAN_VERSION }}

    - if: ${{ steps.restore-phpstan.outputs.cache-hit != 'true' }}
      name: Install PHPStan Dependencies
      run: composer install --working-dir=phpstan
      shell: bash

    - if: ${{ env.STUBS_VERSION != '' }}
      name: Install WordPress stubs as version ${{ env.STUBS_VERSION }}
      run: |
        composer require --dev php-stubs/wordpress-stubs:${{ env.STUBS_VERSION }} --working-dir=phpstan
      shell: bash

    # Make required directory to support loading `..lipemat/actions/..lipemat/actions/..lipemat/actions/extensions.neon`.
    - run: mkdir -p phpstan/vendor/lipemat/phpstan-wordpress
      shell: bash

    # Only save the cache on the master branch.
    - if: ${{ github.ref == 'refs/heads/master' || inputs.alwaysCache == 'true' }}
      name: Save PHPStan to Cache
      uses: actions/cache/save@v4
      id: cache-phpstan
      with:
        path: |
          phpstan
          /tmp/phpstan
        key: ${{ steps.restore-phpstan.outputs.cache-primary-key }}
