###################################################
# Install and cache the phpstan dependency in a resuable action.
#
# Ideally:
# 1. Master installs and caches the phpstan dependency.
# 2. Pull can reuse the cached phpstan dependency.
#
# @version 0.0.2
#
###################################################

name: Install PHPStan
description: Install PHPStan and its dependencies.

runs:
  using: "composite"
  steps:
    - name: Restore PHPStan from Cache
      uses: actions/cache/restore@v4
      id: restore-phpstan
      with:
        path: |
          phpstan
          /tmp/phpstan
        key: phpstan-${{ env.PHPSTAN_VERSION }}
        restore-keys: phpstan-${{ env.PHPSTAN_VERSION }}

    - if: ${{ steps.restore-phpstan.outputs.cache-hit != 'true' }}
      name: Install PHPStan
      uses: actions/checkout@v4
      with:
        repository: lipemat/phpstan-wordpress
        path: phpstan
        ref: ${{ env.PHPSTAN_VERSION }}
        show-progress: false

    - if: ${{ steps.restore-phpstan.outputs.cache-hit != 'true' }}
      name: Install PHPStan Dependencies
      run: composer install --working-dir=phpstan
      shell: bash

    # Make required directory to support loading `..lipemat/actions/..lipemat/actions/..lipemat/actions/extensions.neon`.
    - run: mkdir -p phpstan/vendor/lipemat/phpstan-wordpress
      shell: bash

    # Only save the cache on the master branch.
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Save PHPStan to Cache
      uses: actions/cache/save@v4
      id: cache-phpstan
      with:
        path: |
          phpstan
          /tmp/phpstan
        key: ${{ steps.restore-phpstan.outputs.cache-primary-key }}
