###################################################
# Install the PRO and BASIC plugins.
#
# env:
#   BASIC: The slug of the basic plugin.
#   BASIC_BRANCH: Branch of the basic plugin to override master when used from the pro plugin. If '' then master is used.
#   PRO: The slug of the pro plugin.
#   PRO_BRANCH: Branch of the pro plugin to override master when used from the basic plugin. If '' then master is used.
#
# Token shared by all 4 plugins.
# https://github.com/settings/personal-access-tokens/3757667
#
# @version 0.1.0
#
###################################################

name: Checkout Plugins
description: Checkout the PRO and BASIC plugins.

runs:
  using: "composite"
  steps:
    - name: Determine Plugin refs
      id: determine-pro-ref
      run: |
        if [[ "${{ env.DIR }}" == *"-pro"* ]]; then
          echo "proRef=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "basicRef=${{ env.BASIC_BRANCH }}" >> $GITHUB_ENV
        else
          echo "proRef=${{ env.PRO_BRANCH }}" >> $GITHUB_ENV
          echo "basicRef=${{ github.head_ref }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Checkout the PRO plugin
      uses: actions/checkout@v4
      with:
        repository: lipemat/${{ env.PRO }}
        path: content/plugins/${{ env.PRO }}
        token: ${{ env.TOKEN }}
        # Optional - Override the master branch using a GitHub Action variable.
        ref: ${{ env.proRef }}

    - name: Checkout the Basic plugin
      uses: actions/checkout@v4
      with:
        repository: lipemat/${{ env.BASIC }}
        path: content/plugins/${{ env.BASIC }}
        ref: ${{ env.basicRef }}
