###################################################
# Install the PRO and BASIC plugins.
#
# Secrets must be set in the calling repository.
# - PUBLIC_ACTIONS_PRO_REPO: A personal access token with access to the PRO plugin repository.
#
# Token shared by all 4 plugins.
# https://github.com/settings/personal-access-tokens/3757667
#
# @version 0.0.1
#
###################################################

name: Checkout Plugins
description: Checkout the PRO and BASIC plugins.

runs:
  using: "composite"
  steps:
    - name: Checkout the PRO plugin
      uses: actions/checkout@v4
      with:
        repository: lipemat/${{ env.PRO }}
        path: content/plugins/${{ env.PRO }}
        token: ${{ env.TOKEN }}
        # Optional - Override the master branch using a GitHub Action variable.
        ref: ${{ env.PRO_BRANCH }}

    - name: Checkout the basic plugin
      uses: actions/checkout@v4
      with:
        repository: lipemat/${{ env.BASIC }}
        path: content/plugins/${{ env.BASIC }}
        # Optional - Override the master branch using a GitHub Action variable.
        ref: ${{ env.BASIC_BRANCH }}
