###################################################
# A reusable workflow for running JS Unit on a plugin.
#
# Variables must be set in the calling repository.
# vars:
#   BASIC: The basic plugin slug.
#   BASIC_BRANCH: The branch of the basic plugin.
#   DIR: The directory of the plugin.
#   NODE_VERSION: The version of Node to install.
#   PRO: The pro plugin slug.
#   PRO_BRANCH: The branch of the pro plugin.
#   TOKEN: The token to access the pro repository.
#
###################################################

name: JS Unit - Plugin

env:
  VERSION: 0.2.2
  BASIC: ${{ vars.BASIC }}
  BASIC_BRANCH: ${{ vars.BASIC_BRANCH }}
  DIR: ${{ vars.DIR }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  PRO: ${{ vars.PRO }}
  PRO_BRANCH: ${{ vars.PRO_BRANCH }}
  TOKEN: ${{ secrets.PUBLIC_ACTIONS_PRO_REPO }}

permissions:
  actions: read
  contents: read

on:
  workflow_call:


jobs:
  JS-Unit:
    name: Run JS Unit tests
    runs-on: ubuntu-24.04
    steps:
      - if: ${{ !endsWith(env.DIR, '-pro') }}
        name: Checkout the plugin
        uses: actions/checkout@v4
        with:
          path: ${{ env.DIR }}

      - if: ${{ endsWith(env.DIR, '-pro') }}
        name: Checkout the PRO and BASIC plugins
        uses: lipemat/public-actions/checkout-plugins@version/1

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@version/1

      - name: Validate JS Dist
        run: |
          export NODE_ENV=production
          cd $DIR && yarn dist
        shell: bash

      - name: Validate CSS Modules
        run: cd $DIR && yarn lipemat-js-boilerplate validate-css-modules

      - name: Run JS Tests
        run: cd $DIR && yarn test
        shell: bash
