###################################################
# A reusable workflow for running PHPStan on a plugin.
#
# Variables must be set in the calling repository.
# vars:
#   DIR: The directory of the plugin.
#   PHPCS_VERSION: Version of `lipemat/wp-phpcs` to install.
#
###################################################

name: PHPCS - Plugin

env:
  VERSION: 0.1.0
  DIR: ${{ vars.DIR }}
  PHPCS_VERSION: ${{ vars.PHPCS_VERSION }}

permissions:
  actions: read
  contents: read

on:
  workflow_call:

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the plugin
        uses: actions/checkout@v4
        with:
          path: ${{ env.DIR }}

      - name: Setup PHP
        uses: lipemat/public-actions/setup-php@version/1

      - name: Install PHPCS
        uses: lipemat/public-actions/install-phpcs@version/1
        with:
          alwaysCache: 'true'

      - name: Run PHPCS
        run: phpcs/vendor/bin/phpcs --standard=$DIR/phpcs.xml.dist  -q --report=checkstyle | cs2pr
