###################################################
# A reusable workflow for running PHPStan on a plugin.
#
# Variables must be set in the calling repository.
# vars:
#   DIR: The directory of the plugin.
#   PHPCS_VERSION: Version of `lipemat/wp-phpcs` to install.
#
###################################################

name: PHPCS - Plugin

env:
  VERSION: 0.0.5
  DIR: ${{ vars.DIR }}
  PHPCS_VERSION: ${{ vars.PHPCS_VERSION }}

on:
  workflow_call:

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the plugin
        uses: actions/checkout@v4
        with:
          path: ${{ env.DIR }}

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@v1

      - name: Install PHPCS
        uses: lipemat/public-actions/install-phpcs@v1

      - name: Run PHPCS
        run: phpcs/vendor/bin/phpcs --standard=${{ env.DIR }}/phpcs.xml.dist  -q --report=checkstyle | cs2pr
