###################################################
# A reusable workflow for running PHPStan on a plugin.
#
###################################################

name: PHPStan - Plugin

env:
  VERSION: 0.0.2
  PHPSTAN_VERSION: ${{ inputs.wp }}
  PRO: ${{ inputs.PRO }}
  BASIC: ${{ inputs.BASIC }}
  TOKEN: ${{ secrets.PUBLIC_ACTIONS_PRO_REPO }}
  PRO_BRANCH: ${{ vars.PRO_BRANCH }}
  BASIC_BRANCH: ${{ vars.BASIC_BRANCH }}

on:
  workflow_call:
    inputs:
      wp:
        required: true
        type: string
      php:
        required: true
        type: string
      PRO:
        required: true
        type: string
      BASIC:
        required: true
        type: string
      DIR:
        required: false
        type: string

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the PRO and BASIC plugins
        uses: lipemat/public-actions/checkout-plugins@master

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@master
        env:
          NODE_VERSION: 20.11.0
          PHP_VERSION: ${{ inputs.php }}

      - name: Install PHPStan
        uses: lipemat/public-actions/install-phpstan@master

      - name: Run PHPStan
        run: |
          php phpstan/vendor/bin/phpstan analyze --configuration=${{ inputs.DIR }}/phpstan.neon.dist --memory-limit=2G --no-progress --error-format=checkstyle | cs2pr
