###################################################
# A reusable workflow for running PHPStan on a plugin.
#
# Variables must be set in the calling repository.
# vars:
#   BASIC_BRANCH: The branch of the basic plugin.
#   PHPSTAN_VERSION: The version of PHPStan to install.
#   PRO_BRANCH: The branch of the pro plugin.
# secrets:
#   PUBLIC_ACTIONS_PRO_REPO: The token to access the pro repository.
# inputs:
#   basic: The basic plugin slug.
#   dir: The directory of the plugin.
#   php: The PHP version to use.
#   pro: The pro plugin slug.
#   stubs: The version of the `lipemat/phpstan-wordpress` to install.
#
###################################################

name: PHPStan - Plugin

env:
  VERSION: 0.0.3
  BASIC: ${{ inputs.basic }}
  BASIC_BRANCH: ${{ vars.BASIC_BRANCH }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  PHPSTAN_VERSION: ${{ vars.PHPSTAN_VERSION }}
  PRO: ${{ inputs.pro }}
  PRO_BRANCH: ${{ vars.PRO_BRANCH }}
  STUBS_VERSION: ${{ inputs.stubs }}
  TOKEN: ${{ secrets.PUBLIC_ACTIONS_PRO_REPO }}

on:
  workflow_call:
    inputs:
      basic:
        required: true
        type: string
      dir:
        required: true
        type: string
      php:
        required: true
        type: string
      pro:
        required: true
        type: string
      stubs:
        required: true
        type: string

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the PRO and BASIC plugins
        uses: lipemat/public-actions/checkout-plugins@master

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@master
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          PHP_VERSION: ${{ inputs.php }}

      - name: Install PHPStan
        uses: lipemat/public-actions/install-phpstan@master
        env:
          PHPSTAN_VERSION: ${{ vars.PHPSTAN_VERSION }}

      - name: Run PHPStan
        run: |
          php phpstan/vendor/bin/phpstan analyze --configuration=${{ inputs.dir }}/phpstan.neon.dist --memory-limit=2G --no-progress --error-format=checkstyle | cs2pr
