###################################################
# A reusable workflow for running PHPStan on a plugin.
#
# Variables must be set in the calling repository.
# vars:
#   BASIC: The basic plugin slug.
#   BASIC_BRANCH: The branch of the basic plugin.
#   DIR: The directory of the plugin.
#   NODE_VERSION: The version of Node to install.
#   PHPSTAN_VERSION: The version of PHPStan to install.
#   PRO: The pro plugin slug.
#   PRO_BRANCH: The branch of the pro plugin.
# secrets:
#   PUBLIC_ACTIONS_PRO_REPO: The token to access the pro repository.
# inputs:
#   php: The PHP version to use.
#   stubs: The version of the `lipemat/phpstan-wordpress` to install.
#
###################################################

name: PHPStan - Plugin

env:
  VERSION: 0.0.5
  BASIC: ${{ vars.BASIC }}
  BASIC_BRANCH: ${{ vars.BASIC_BRANCH }}
  DIR: ${{ vars.DIR }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  PHPSTAN_VERSION: ${{ vars.PHPSTAN_VERSION }}
  PRO: ${{ vars.PRO }}
  PRO_BRANCH: ${{ vars.PRO_BRANCH }}
  STUBS_VERSION: ${{ inputs.stubs }}
  TOKEN: ${{ secrets.PUBLIC_ACTIONS_PRO_REPO }}

on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
      stubs:
        required: true
        type: string

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the PRO and BASIC plugins
        uses: lipemat/public-actions/checkout-plugins@version/1

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@version/1
        env:
          NODE_VERSION: ${{ env.NODE_VERSION }}
          PHP_VERSION: ${{ inputs.php }}

      - name: Install PHPStan
        uses: lipemat/public-actions/install-phpstan@version/1
        env:
          PHPSTAN_VERSION: ${{ env.PHPSTAN_VERSION }}

      - name: Run PHPStan
        run: |
          php phpstan/vendor/bin/phpstan analyze --configuration=${{ env.DIR }}/phpstan.neon.dist --memory-limit=2G --no-progress --error-format=checkstyle | cs2pr
