###################################################
# Install and cache the dependencies when `master` is pushed
# for other workflows to use.
#
# Most workflows will reuse the same cached
# dependencies as the last release. Having master populate the
# cache makes them accessible to all pull requests and deployments.
#
# Variables must be set in the calling repository.
# https://github.com/lipemat/<plugin>/settings/variables/actions
# vars:
#   BASIC: The basic plugin slug.
#   BASIC_BRANCH: The branch of the basic plugin.
#   DIR: The directory of the plugin.
#   NODE_VERSION: The version of Node to install.
#   PHPCS_VERSION: The version of PHPCS to install.
#   PHPSTAN_VERSION: The version of PHPStan to install.
#   PHP_VERSION: The version of PHP to install.
#   PRO: The pro plugin slug.
#   PRO_BRANCH: The branch of the pro plugin.
#   WP_UNIT_VERSION: The version of WP-Unit to install.
#
###################################################

name: Populate Caches - Plugin
env:
  VERSION: 1.2.3
  BASIC: ${{ vars.BASIC }}
  BASIC_BRANCH: ${{ vars.BASIC_BRANCH }}
  DIR: ${{ vars.DIR }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  PHPCS_VERSION: ${{ vars.PHPCS_VERSION }}
  PHPSTAN_VERSION: ${{ vars.PHPSTAN_VERSION }}
  PHP_VERSION: ${{ vars.PHP_VERSION }}
  PRO: ${{ vars.PRO }}
  PRO_BRANCH: ${{ vars.PRO_BRANCH }}
  WP_UNIT_VERSION: ${{ vars.WP_UNIT_VERSION }}

on:
  workflow_call:


jobs:
  populate:
    name: Populate all caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the PRO and BASIC plugins
        uses: lipemat/public-actions/checkout-plugins@version/1

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@version/1

      - name: Populate WP-Unit Cache
        uses: lipemat/public-actions/install-wp-unit@version/1

      - name: Populate PHPCS Cache
        uses: lipemat/public-actions/install-phpcs@version/1

      - name: Install Translations Dependencies
        uses: lipemat/public-actions/install-translate@version/1
