###################################################
# Install and cache the dependencies when `master` is pushed
# for other workflows to use.
#
# Most workflows will reuse the same cached
# dependencies as the last release. Having master populate the
# cache makes them accessible to all pull requests and deployments.
#
# Variables must be set in the calling repository.
# https://github.com/lipemat/<plugin>/settings/variables/actions
# vars:
#   DIR: The directory of the plugin.
#   NODE_VERSION: The version of Node to install.
#   PHPCS_VERSION: The version of PHPCS to install.
#   PHPSTAN_VERSION: The version of PHPStan to install.
#   PHP_VERSION: The version of PHP to install.
#   WP_UNIT_VERSION: The version of WP-Unit to install.
#
###################################################

name: Populate Caches - Plugin
env:
  VERSION: 1.3.2
  DIR: ${{ vars.DIR }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}
  PHPCS_VERSION: ${{ vars.PHPCS_VERSION }}
  PHPSTAN_VERSION: ${{ vars.PHPSTAN_VERSION }}
  PHP_VERSION: ${{ vars.PHP_VERSION }}
  WP_UNIT_VERSION: ${{ vars.WP_UNIT_VERSION }}

on:
  workflow_call:


jobs:
  populate:
    name: Populate all caches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@version/1

      - name: Populate WP-Unit Cache
        uses: lipemat/public-actions/install-wp-unit@version/1

      - name: Populate PHPCS Cache
        uses: lipemat/public-actions/install-phpcs@version/1

      - name: Populate Translations Composer Cache
        uses: lipemat/public-actions/install-translate@version/1
        with:
          dir: .
