###################################################
# A reusable workflow for publishing a Node package.
#
# The preferred method of authentication is to use Trusted Publisher in NPM.js settings.
# @link https://docs.npmjs.com/trusted-publishers
#
# 1. Select your publisher: GitHub Actions
# 2. Publishing access: Require two-factor authentication and disallow tokens.
#
# @requires Node version >= 22.21.1
#
# inputs:
#   beta: Run the workflow for beta releases.
#   nodeVersion: The version of Node to install.
#   withInstall: Run `yarn install` before publishing.
#
#
###################################################
name: Publish Node Package

env:
  VERSION: 1.0.0
  TZ: 'America/New_York'

permissions:
  actions: read
  contents: read
  id-token: write  # Required for OIDC

on:
  workflow_call:
    inputs:
      beta:
        description: Run the workflow for beta releases.
        required: true
        type: boolean
      nodeVersion:
        required: true
        type: string
      withInstall:
        required: true
        type: boolean

jobs:
  publish:
    name: Publish on npm.js
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: lipemat/public-actions/setup-node@version/1
        env:
          NODE_VERSION: ${{ inputs.nodeVersion }}

      - name: Upgrade npm for Trusted Publishing
        shell: bash
        # Minium required version is 11.5.1
        run: npm i -g npm@^11.5.1

      - if: ${{ inputs.withInstall }}
        name: Install node modules
        shell: bash
        run: yarn install --frozen-lockfile

      - if: ${{ inputs.beta == false}}
        name: Publish to NPM
        run: npm publish --access public

      - if: ${{ inputs.beta == true}}
        name: Publish Beta to NPM
        run: npm publish --tag beta --access public
