##############################
# Test and lint files in a pull request.
#
# Variables must be set in the calling repository.
# vars:
#   BASIC: The basic plugin slug.
#   BASIC_BRANCH: The branch of the basic plugin.
#   DIR: The directory of the plugin.
#   PHPCS_VERSION: The version of `lipemat/wp-phpcs` to install.
#   PHPSTAN_VERSION: The version of PHPStan to install.
#   PRO: The pro plugin slug.
#   PRO_BRANCH: The branch of the pro plugin.
#
# @version 0.0.4
#
##############################

name: Test & Lint Files

on:
  workflow_call:

jobs:
  php-lint:
    strategy:
      matrix:
        php: [ 7.4, 8.0, 8.1, 8.2, 8.3 ]
    uses: lipemat/public-actions/.github/workflows/php-lint.yml@master
    with:
      php: ${{ matrix.php }}

  wp-unit:
    strategy:
      matrix:
        wp: [ 6.2.6, 6.6.1 ]
        php: [ 7.4, 8.3 ]
        multisite: [ 'single', 'multisite' ]
    uses: lipemat/public-actions/.github/workflows/wp-unit-plugin.yml@master
    with:
      basic: ${{ vars.BASIC }}
      pro: ${{ vars.PRO }}
      multisite: ${{ matrix.multisite }}
      php: ${{ matrix.php }}
      wp: ${{ matrix.wp }}
    secrets: inherit

  phpstan:
    strategy:
      matrix:
        combination:
          - php: 7.4
            stubs: 6.2.5
          - php: 8.3
            stubs: 6.6.0
    uses: lipemat/public-actions/.github/workflows/phpstan-plugin.yml@master
    with:
      basic: ${{ vars.BASIC }}
      dir: ${{ vars.DIR }}
      pro: ${{ vars.PRO }}
      php: ${{ matrix.combination.php }}
      stubs: ${{ matrix.combination.stubs }}
    secrets: inherit

  phpcs:
    uses: lipemat/public-actions/.github/workflows/phpcs-plugin.yml@master
    with:
      dir: ${{ vars.DIR }}
