###################################################
# A reusable workflow for running WP-Unit tests on a plugin.
#
# Variables must be set in the calling repository.
# vars:
#   BASIC: The basic plugin slug.
#   BASIC_BRANCH: The branch of the basic plugin.
#   DIR: The directory of the plugin.
#   PHP_VERSION: The PHP version to use for global actions which don't use the PHP_VERSION input.
#   PRO_BRANCH: The branch of the pro plugin.
#   WP_UNIT_VERSION: The version of WP-Unit to install.
# secrets:
#   PUBLIC_ACTIONS_PRO_REPO: The token to access the pro repository.
# inputs:
#   multisite: The type of multisite to test.
#   php: The PHP version to use.
#   wp: The version of WordPress to test.
#
###################################################

name: WP Unit - Plugin

env:
  VERSION: 1.4.0
  BASIC: ${{ vars.BASIC }}
  BASIC_BRANCH: ${{ vars.BASIC_BRANCH }}
  DIR: ${{ vars.DIR }}
  PRO: ${{ vars.PRO }}
  PRO_BRANCH: ${{ vars.PRO_BRANCH }}
  TOKEN: ${{ secrets.PUBLIC_ACTIONS_PRO_REPO }}
  WP_UNIT_VERSION: ${{ vars.WP_UNIT_VERSION }}

on:
  workflow_call:
    inputs:
      multisite:
        description: Run tests on multisite or single site. Values include 'single' or 'multisite'.
        required: true
        type: string
      php:
        description: The PHP version to use.
        required: true
        type: string
      skipDatabaseInstall:
        description: Skip the wp-unit install of database step in favor of importing the dump.
        required: false
        type: boolean
        default: true
      wp:
        description: The version of WordPress to test.
        required: true
        type: string

jobs:
  wp-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WordPress Core
        uses: actions/checkout@v4
        with:
          repository: wordpress/wordpress
          path: wp
          ref: ${{ inputs.wp }}

      - name: Checkout the PRO and BASIC plugins
        uses: lipemat/public-actions/checkout-plugins@version/1

      - name: Checkout the public-actions repository
        uses: actions/checkout@v4
        with:
          repository: lipemat/public-actions
          path: public-actions
          ref: version/1

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@version/1
        env:
          NODE_VERSION: 20.11.0
          PHP_VERSION: ${{ inputs.php }}

      - name: Install Memcached Service
        uses: lipemat/public-actions/memcache-service@version/1

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE `wp-unit`;' -u root -proot    

      - if: ${{ inputs.skipDatabaseInstall == true }}
        name: Import MySQL Dump
        run: |
          unzip -p public-actions/resources/plugins/config/wp-unit.sql.zip | mysql -u root -proot wp-unit

      - name: Add object-cache file to wp-content
        run: |
          cp public-actions/resources/plugins/object-cache.php content/object-cache.php

      - name: Install WP-Unit
        uses: lipemat/public-actions/install-wp-unit@version/1
        with:
          alwaysCache: 'true'

      - name: Add WP-Unit Config
        run: cp public-actions/resources/plugins/config/wp-unit-local-config.php content/plugins/${{ env.PRO }}/dev/wp-unit/local-config.php

      - name: Build PRO Translations
        uses: lipemat/public-actions/plugin-translations@version/1
        with:
          dir: content/plugins/${{ env.PRO }}

      - name: Build BASIC Translations
        uses: lipemat/public-actions/plugin-translations@version/1
        with:
          dir: content/plugins/${{ env.BASIC }}

      - if: ${{ fromJSON(inputs.php) < 8.1 }}
        name: Checkout PHPUnit 9
        run: |
          cd wp-unit
          composer require phpunit/phpunit:^9.6.20 --dev --no-scripts --with-dependencies

      - if: ${{ fromJSON(inputs.php) < 8.1 }}
        name: Run WP-Unit Legacy
        env:
          MULTISITE: ${{ inputs.multisite }}
        run: |
          php wp-unit/vendor/bin/phpunit --configuration content/plugins/${{ env.PRO }}/dev/wp-unit/phpunit-legacy.xml.dist --fail-on-warning
        shell: bash

      - if: ${{ fromJSON(inputs.php) >= 8.1 }}
        name: Run WP-Unit
        env:
          MULTISITE: ${{ inputs.multisite }}
        run: |
          php wp-unit/vendor/bin/phpunit --configuration content/plugins/${{ env.PRO }}/dev/wp-unit/phpunit.xml.dist --fail-on-warning
        shell: bash
