###################################################
# A reusable workflow for running WP-Unit tests on a plugin.
#
# Variables must be set in the calling repository.
# vars:
#   BASIC: The basic plugin slug.
#   BASIC_BRANCH: The branch of the basic plugin.
#   DIR: The directory of the plugin.
#   PRO_BRANCH: The branch of the pro plugin.
#   WP_UNIT_VERSION: The version of WP-Unit to install.
# secrets:
#   PUBLIC_ACTIONS_PRO_REPO: The token to access the pro repository.
# inputs:
#   multisite: The type of multisite to test.
#   php: The PHP version to use.
#   wp: The version of WordPress to test.
#
###################################################

name: WP Unit - Plugin

env:
  VERSION: 1.3.0
  BASIC: ${{ vars.BASIC }}
  BASIC_BRANCH: ${{ vars.BASIC_BRANCH }}
  DIR: ${{ vars.DIR }}
  PRO: ${{ vars.PRO }}
  PRO_BRANCH: ${{ vars.PRO_BRANCH }}
  TOKEN: ${{ secrets.PUBLIC_ACTIONS_PRO_REPO }}
  WP_UNIT_VERSION: ${{ vars.WP_UNIT_VERSION }}

on:
  workflow_call:
    inputs:
      multisite:
        required: true
        type: string
      php:
        required: true
        type: string
      wp:
        required: true
        type: string

jobs:
  wp-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WordPress Core
        uses: actions/checkout@v4
        with:
          repository: wordpress/wordpress
          path: wp
          ref: ${{ inputs.wp }}

      - name: Checkout the PRO and BASIC plugins
        uses: lipemat/public-actions/checkout-plugins@master

      - name: Checkout the public-actions repository
        uses: actions/checkout@v4
        with:
          repository: lipemat/public-actions
          path: public-actions

      - name: Setup Node and PHP
        uses: lipemat/public-actions/setup-dependencies@master
        env:
          NODE_VERSION: 20.11.0
          PHP_VERSION: ${{ inputs.php }}

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE `wp-unit`;' -u root -proot    

      - name: Import MySQL Dump
        run: |
          unzip -p public-actions/resources/plugins/config/wp-unit.sql.zip | mysql -u root -proot wp-unit

      - name: Install WP-Unit
        uses: lipemat/public-actions/install-wp-unit@master

      - name: Add WP-Unit Config
        run: cp public-actions/resources/plugins/config/wp-unit-local-config.php content/plugins/${{ inputs.pro }}/dev/wp-unit/local-config.php



      - name: Install Translations Dependencies
        run: |
          cd ${{ env.DIR }}/dev/translate-cli
          composer install
        shell: bash

      - name: Install WP-CLI
        uses: lipemat/public-actions/install-wp-cli@master

      - name: Generate JS translations
        run: |
          cd ${{ env.DIR }}/dev/translate-cli
          php command.php
        shell: bash

      - name: Generate PHP translations
        run: |
          cd ${{ env.DIR }}/languages
          wp i18n make-php .
        shell: bash



      - name: Run WP-Unit
        env:
          MULTISITE: ${{ inputs.multisite }}
        run: |
          if [ $(echo "${{ inputs.php }} < 8.1" | bc) -eq 1 ]; then
            php wp-unit/vendor/bin/phpunit --configuration ${{ env.DIR }}/dev/wp-unit/phpunit-legacy.xml.dist"
          else
            php wp-unit/vendor/bin/phpunit --configuration ${{ env.DIR }}/dev/wp-unit/phpunit.xml.dist
          fi
