###################################################
# Local action to set up the action's environment.
#
# @version 2.1.0
#
###################################################

name: Setup Dependencies
description: Setup Node, Yarn, PHP, and ts-node

runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
        registry-url: 'https://registry.npmjs.org'

    - name: Install yarn
      shell: bash
      run: corepack enable

    - name: Install ts-node
      shell: bash
      run: npm install -g ts-node

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{env.PHP_VERSION}}
        tools: cs2pr
