###################################################
# Local action to set up the action's environment.
#
# @version 2.1.0
#
# @deprecated in favor of combining setup-node and setup-php
#
###################################################

name: Setup Dependencies
description: Setup Node, Yarn, PHP, and ts-node

runs:
  using: "composite"
  steps:
    - uses: lipemat/public-actions/setup-node@version/1

    - uses: lipemat/public-actions/setup-php@version/1
